[versions]
agp = "8.10.0"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.9.0"
# Removing activityCompose and composeBom
# activityCompose = "1.10.1"
# composeBom = "2025.05.00"
# Not using appcompat
# appcompat = "1.7.0"
navigationFragment = "2.9.0"
navigationSafeArgsGradlePlugin = "2.9.0"
# Adding standard activity
activity = "1.9.0"
# For material components (non-AppCompat)
material = "1.12.0"
constraintlayout = "2.1.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigationSafeArgsGradlePlugin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
# Removing all Compose-related libraries
# androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
# androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
# androidx-ui = { group = "androidx.compose.ui", name = "ui" }
# androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
# androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
# androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
# androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
# androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
# androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
# Not using AppCompat
# androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigationFragment" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragment" }
# Adding standard activity
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
# Adding material components (non-AppCompat)
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
# Adding constraintlayout
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
# Removing Compose plugin
# kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
navigation-safe-args = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigationSafeArgsGradlePlugin" }